apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: sample-app
    newName: your-docker-image
    newTag: latest
